# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 718dbe6d2f4bce7092754ba44264239e258d6986daef8d463321025657cececae1d414896d14d9534c9f1345b818ffe31bcccc67d908be2e05cff3dbba6d297b

test:
  secret_key_base: 3ffbe3aeef979be0741370d5e82c30e8d12309f8dcf2119fed9e1c77b0db893b99e959523479783db38bc3559e7f74581ecd251f8d9ac999c740a070d9a73784

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
